In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("data.csv")

In [3]:
data.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [4]:
data2 = data.drop(["Unnamed: 0","ID"],axis=1)
data2.head()

,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,Value,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,https://cdn.sofifa.org/teams/2/light/241.png,€110.5M,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,https://cdn.sofifa.org/teams/2/light/45.png,€77M,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,https://cdn.sofifa.org/teams/2/light/73.png,€118.5M,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,https://cdn.sofifa.org/teams/2/light/11.png,€72M,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,https://cdn.sofifa.org/teams/2/light/10.png,€102M,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [5]:
data2.describe()

,Age,Overall,Potential,Special,International Reputation,Weak Foot,Skill Moves,Jersey Number,Crossing,Finishing,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
count,18207.000000,18207.000000,18207.000000,18207.000000,18159.000000,18159.000000,18159.000000,18147.000000,18159.000000,18159.000000,...,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000
mean,25.122206,66.238699,71.307299,1597.809908,1.113222,2.947299,2.361308,19.546096,49.734181,45.550911,...,48.548598,58.648274,47.281623,47.697836,45.661435,16.616223,16.391596,16.232061,16.388898,16.710887
std,4.669943,6.908930,6.136496,272.586016,0.394031,0.660456,0.756164,15.947765,18.364524,19.525820,...,15.704053,11.436133,19.904397,21.664004,21.289135,17.695349,16.906900,16.502864,17.034669,17.955119
min,16.000000,46.000000,48.000000,731.000000,1.000000,1.000000,1.000000,1.000000,5.000000,2.000000,...,5.000000,3.000000,3.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,21.000000,62.000000,67.000000,1457.000000,1.000000,3.000000,2.000000,8.000000,38.000000,30.000000,...,39.000000,51.000000,30.000000,27.000000,24.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,25.000000,66.000000,71.000000,1635.000000,1.000000,3.000000,2.000000,17.000000,54.000000,49.000000,...,49.000000,60.000000,53.000000,55.000000,52.000000,11.000000,11.000000,11.000000,11.000000,11.000000
75%,28.000000,71.000000,75.000000,1787.000000,1.000000,3.000000,3.000000,26.000000,64.000000,62.000000,...,60.000000,67.000000,64.000000,66.000000,64.000000,14.000000,14.000000,14.000000,14.000000,14.000000
max,45.000000,94.000000,95.000000,2346.000000,5.000000,5.000000,5.000000,99.000000,93.000000,95.000000,...,92.000000,96.000000,94.000000,93.000000,91.000000,90.000000,92.000000,91.000000,90.000000,94.000000

In [6]:
#Treating NaN Values
for i in data2:
    if data2[i].dtype=='object':
        data2[i]=data2[i].fillna(str(data2[i].mode()[0]))
    else:
        data2[i]=data2[i].fillna(data2[i].mean())

In [7]:
def Scaling(data):
    return data/data.max()

In [8]:
#Looking For Columns That have URL as values
import re
for i in data2:
        if len(re.findall('http.*',str(data.loc[0,i])))>0:
                print(i)

Photo
Flag
Club Logo

In [9]:
data2=data2.drop(['Photo','Flag','Club Logo'],axis=1)

In [10]:
data2.head()

,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Special,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M,€565K,2202,Left,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M,€405K,2228,Right,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,€118.5M,€290K,2143,Right,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,De Gea,27,Spain,91,93,Manchester United,€72M,€260K,1471,Right,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,K. De Bruyne,27,Belgium,91,92,Manchester City,€102M,€355K,2281,Right,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [11]:
#Converting columns with  format '€...M or €...K' from string to numerical with 'K' or 1000 units 
for i in data2:
    if len(re.findall('.[0-9][A-Z]$',str(data2.loc[0,i])))>0:
        for j in data2.index:
            a=str(data2.loc[j,i])[1:]
            if a=='0':
                data2.loc[j,i]=float(a)
                continue
            a=re.findall('(.*)[A-Z]$',a)
            a=''.join(a)
            if str(data2.loc[j,i])[-1]=='M':
                data2.loc[j,i]=str(float(a)*1000)
            else:
                data2.loc[j,i]=float(a)
        data2[i]=data2[i].astype('float64')

In [12]:
data2.head()

,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Special,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,2202,Left,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,226500.0
1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,2228,Right,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,127100.0
2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,2143,Right,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,228100.0
3,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,1471,Right,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,138600.0
4,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,2281,Right,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,196400.0

In [13]:
features=data2.loc[:,'Age':'GKReflexes']

In [14]:
features.head()

,Age,Nationality,Overall,Potential,Club,Value,Wage,Special,Preferred Foot,International Reputation,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
0,31,Argentina,94,94,FC Barcelona,110500.0,565.0,2202,Left,5.0,...,75.0,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0
1,33,Portugal,94,94,Juventus,77000.0,405.0,2228,Right,5.0,...,85.0,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0
2,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,2143,Right,5.0,...,81.0,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0
3,27,Spain,91,93,Manchester United,72000.0,260.0,1471,Right,4.0,...,40.0,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0
4,27,Belgium,91,92,Manchester City,102000.0,355.0,2281,Right,4.0,...,79.0,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0

In [15]:
target=data2.iloc[:,-1]

In [16]:
target

0        226500.0
1        127100.0
2        228100.0
3        138600.0
4        196400.0
           ...
18202       143.0
18203       113.0
18204       165.0
18205       143.0
18206       165.0
Name: Release Clause, Length: 18207, dtype: float64

In [78]:
correlation_mat=features.join(target).corr()
high_correlation_mat=correlation_mat[abs(correlation_mat['Release Clause'])>0.3]
features2=features.loc[:,high_correlation_mat.index[:-1]]

In [79]:
features2.head()

,Overall,Potential,Value,Wage,Special,International Reputation,ShortPassing,Reactions,Vision,Composure
0,94,94,110500.0,565.0,2202,5.0,90.0,95.0,94.0,96.0
1,94,94,77000.0,405.0,2228,5.0,81.0,96.0,82.0,95.0
2,92,93,118500.0,290.0,2143,5.0,84.0,94.0,87.0,94.0
3,91,93,72000.0,260.0,1471,4.0,50.0,90.0,68.0,68.0
4,91,92,102000.0,355.0,2281,4.0,92.0,91.0,94.0,88.0

In [80]:
features2.dtypes

Overall                       int64
Potential                     int64
Value                       float64
Wage                        float64
Special                       int64
International Reputation    float64
ShortPassing                float64
Reactions                   float64
Vision                      float64
Composure                   float64
dtype: object

In [83]:
def scaling(data):
    for i in data.columns:
        data[i]=(data[i]-data[i].min())/(data[i].max()-data[i].min())
def getminmax(data):
    min_max=[];
    for i in data.columns:
        min_max.append((data[i].min(),data[i].max()))
    return min_max

In [82]:
min_max=getminmax(features2)
min_max

[(46, 94),
 (48, 95),
 (0.0, 118500.0),
 (0.0, 565.0),
 (731, 2346),
 (1.0, 5.0),
 (7.0, 93.0),
 (21.0, 96.0),
 (10.0, 94.0),
 (3.0, 96.0)]

In [44]:
scaling(features2)
features2.head()

,Overall,Potential,Value,Wage,Special,International Reputation,ShortPassing,Reactions,Vision,Composure
0,1.000000,0.978723,0.932489,1.000000,0.910836,1.00,0.965116,0.986667,1.000000,1.000000
1,1.000000,0.978723,0.649789,0.716814,0.926935,1.00,0.860465,1.000000,0.857143,0.989247
2,0.958333,0.957447,1.000000,0.513274,0.874303,1.00,0.895349,0.973333,0.916667,0.978495
3,0.937500,0.957447,0.607595,0.460177,0.458204,0.75,0.500000,0.920000,0.690476,0.698925
4,0.937500,0.936170,0.860759,0.628319,0.959752,0.75,0.988372,0.933333,1.000000,0.913978

In [45]:
features2=pd.DataFrame(features2,columns=high_correlation_mat.index[:-1])

In [46]:
features2.head()

,Overall,Potential,Value,Wage,Special,International Reputation,ShortPassing,Reactions,Vision,Composure
0,1.000000,0.978723,0.932489,1.000000,0.910836,1.00,0.965116,0.986667,1.000000,1.000000
1,1.000000,0.978723,0.649789,0.716814,0.926935,1.00,0.860465,1.000000,0.857143,0.989247
2,0.958333,0.957447,1.000000,0.513274,0.874303,1.00,0.895349,0.973333,0.916667,0.978495
3,0.937500,0.957447,0.607595,0.460177,0.458204,0.75,0.500000,0.920000,0.690476,0.698925
4,0.937500,0.936170,0.860759,0.628319,0.959752,0.75,0.988372,0.933333,1.000000,0.913978

In [47]:
features2.describe()

,Overall,Potential,Value,Wage,Special,International Reputation,ShortPassing,Reactions,Vision,Composure
count,18207.000000,18207.000000,18207.000000,18207.000000,18207.000000,18207.000000,18207.000000,18207.000000,18207.000000,18207.000000
mean,0.421640,0.495900,0.020343,0.017224,0.536724,0.028306,0.601008,0.544488,0.516677,0.598369
std,0.143936,0.130564,0.047215,0.038937,0.168784,0.098378,0.170699,0.119981,0.168193,0.122807
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.333333,0.404255,0.002532,0.001770,0.449536,0.000000,0.546512,0.466667,0.404762,0.516129
50%,0.416667,0.489362,0.005696,0.005310,0.559752,0.000000,0.639535,0.546667,0.535714,0.602151
75%,0.520833,0.574468,0.016878,0.015929,0.653870,0.000000,0.709302,0.626667,0.642857,0.688172
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [48]:
from sklearn.model_selection import train_test_split

In [49]:
X_train,X_test,Y_train,Y_test=train_test_split(features2,target,test_size=0.2)

In [50]:
X_train,X_val,Y_train,Y_val=train_test_split(X_train,Y_train,test_size=0.3)

In [51]:
np.savez('Testing_Data.npz',inputs=X_test,target=Y_test)

In [52]:
np.savez('Training_Data.npz',inputs=X_train,target=Y_train)

In [53]:
np.savez('Validation_Data.npz',inputs=X_val,target=Y_val)

In [54]:
len(Y_train),len(Y_val),len(Y_test)

(10195, 4370, 3642)

In [55]:
train_data=np.load('Training_Data.npz')

In [56]:
val_data=np.load('Validation_Data.npz')

In [57]:
input_size_=train_data['inputs'].shape[1]
hidden_layer_size=15
output_size=1

In [58]:
import tensorflow as tf

In [59]:
model=tf.keras.Sequential([
    tf.keras.layers.Dense(hidden_layer_size),
    tf.keras.layers.Dense(hidden_layer_size,activation='linear',
                        kernel_initializer = tf.random_uniform_initializer(np.sqrt(6/(input_size_+output_size))),
                        bias_initializer =  tf.random_uniform_initializer(np.sqrt(6/(input_size_+output_size)))),
    tf.keras.layers.Dense(hidden_layer_size, activation='linear',
                        kernel_initializer = tf.random_uniform_initializer(np.sqrt(6/(input_size_+output_size))),
                        bias_initializer =  tf.random_uniform_initializer(np.sqrt(6/(input_size_+output_size)))),
    tf.keras.layers.Dense(hidden_layer_size, activation='linear',
                        kernel_initializer = tf.random_uniform_initializer(np.sqrt(6/(input_size_+output_size))),
                        bias_initializer =  tf.random_uniform_initializer(np.sqrt(6/(input_size_+output_size)))),
    tf.keras.layers.Dense(hidden_layer_size, activation='linear',
                        kernel_initializer = tf.random_uniform_initializer(np.sqrt(6/(input_size_+output_size))),
                        bias_initializer =  tf.random_uniform_initializer(np.sqrt(6/(input_size_+output_size)))),
    tf.keras.layers.Dense(output_size, activation='linear',
                        kernel_initializer = tf.random_uniform_initializer(np.sqrt(6/(input_size_+output_size))),
                        bias_initializer =  tf.random_uniform_initializer(np.sqrt(6/(input_size_+output_size))))
])

In [60]:
callback = tf.keras.callbacks.EarlyStopping(monitor='loss', patience=5)

In [61]:
model.compile(optimizer='adam',loss='mean_squared_error',metrics=['mae'])

In [62]:
batch_size_=int(train_data['inputs'].shape[0]/10)
model.fit(train_data['inputs'],train_data['target'],batch_size=batch_size_,callbacks=[callback],epochs=200,validation_data=(val_data['inputs'],val_data['target']),verbose=2,validation_steps=1)

Train on 10195 samples, validate on 4370 samples
Epoch 1/200
10195/10195 - 2s - loss: 131160551.3872 - mae: 3739.6719 - val_loss: 22278968.2929 - val_mae: 3453.6147
Epoch 2/200
10195/10195 - 0s - loss: 125760215.6036 - mae: 3770.0286 - val_loss: 21164731.6668 - val_mae: 3603.2334
Epoch 3/200
10195/10195 - 0s - loss: 120535928.7549 - mae: 3963.3845 - val_loss: 20137079.7272 - val_mae: 3898.1763
Epoch 4/200
10195/10195 - 0s - loss: 115631654.2580 - mae: 4284.0283 - val_loss: 19294453.9368 - val_mae: 4316.5298
Epoch 5/200
10195/10195 - 0s - loss: 111826206.2336 - mae: 4726.4019 - val_loss: 18822787.0517 - val_mae: 4805.7720
Epoch 6/200
10195/10195 - 0s - loss: 109566382.2786 - mae: 5157.9814 - val_loss: 18676215.2110 - val_mae: 5139.2646
Epoch 7/200
10195/10195 - 0s - loss: 108462399.5072 - mae: 5382.6172 - val_loss: 18531115.2073 - val_mae: 5224.1113
Epoch 8/200
10195/10195 - 0s - loss: 107465447.5973 - mae: 5412.4287 - val_loss: 18320996.9410 - val_mae: 5180.6968
Epoch 9/200
10195/10195 - 0s - loss: 106331212.7245 - mae: 5325.4370 - val_loss: 18070644.7304 - val_mae: 5053.8438
Epoch 10/200
10195/10195 - 0s - loss: 105176252.3947 - mae: 5174.5176 - val_loss: 17816716.4595 - val_mae: 4963.1851
Epoch 11/200
10195/10195 - 0s - loss: 103737788.3474 - mae: 5240.3687 - val_loss: 17568610.2462 - val_mae: 5090.3955
Epoch 12/200
10195/10195 - 0s - loss: 102124622.4428 - mae: 5279.0127 - val_loss: 17227517.1350 - val_mae: 5020.8657
Epoch 13/200
10195/10195 - 0s - loss: 100270375.8450 - mae: 5094.4038 - val_loss: 16829490.6050 - val_mae: 4825.7656
Epoch 14/200
10195/10195 - 0s - loss: 98177045.5025 - mae: 5114.8237 - val_loss: 16410936.7048 - val_mae: 4987.3921
Epoch 15/200
10195/10195 - 0s - loss: 95415269.9184 - mae: 5148.4443 - val_loss: 15863562.5501 - val_mae: 4850.6108
Epoch 16/200
10195/10195 - 0s - loss: 92422596.9514 - mae: 4882.7344 - val_loss: 15202975.3968 - val_mae: 4544.1157
Epoch 17/200
10195/10195 - 0s - loss: 88858653.9867 - mae: 4719.6675 - val_loss: 14489329.3565 - val_mae: 4494.1431
Epoch 18/200
10195/10195 - 0s - loss: 84750590.8732 - mae: 4499.0557 - val_loss: 13633841.3144 - val_mae: 4177.8481
Epoch 19/200
10195/10195 - 0s - loss: 80135728.4600 - mae: 4332.2573 - val_loss: 12655327.0938 - val_mae: 4071.8164
Epoch 20/200
10195/10195 - 0s - loss: 74474660.4767 - mae: 3988.8931 - val_loss: 11588675.2027 - val_mae: 3578.9058
Epoch 21/200
10195/10195 - 0s - loss: 69002505.9077 - mae: 3551.8384 - val_loss: 10477207.8316 - val_mae: 3380.5415
Epoch 22/200
10195/10195 - 0s - loss: 62631686.9602 - mae: 3538.3489 - val_loss: 9292134.6160 - val_mae: 3290.7234
Epoch 23/200
10195/10195 - 0s - loss: 55978804.3217 - mae: 3197.3813 - val_loss: 8139813.0398 - val_mae: 2822.0598
Epoch 24/200
10195/10195 - 0s - loss: 49864153.3155 - mae: 2915.3752 - val_loss: 7153989.0682 - val_mae: 2810.5544
Epoch 25/200
10195/10195 - 0s - loss: 44204193.1294 - mae: 2861.6350 - val_loss: 6389283.4330 - val_mae: 2600.5903
Epoch 26/200
10195/10195 - 0s - loss: 40300222.7892 - mae: 2722.3145 - val_loss: 5979971.4197 - val_mae: 2818.4443
Epoch 27/200
10195/10195 - 0s - loss: 39483513.8792 - mae: 3458.2571 - val_loss: 5684489.4014 - val_mae: 2814.4792
Epoch 28/200
10195/10195 - 0s - loss: 35260446.9585 - mae: 2968.4871 - val_loss: 5481883.7533 - val_mae: 2690.2947
Epoch 29/200
10195/10195 - 0s - loss: 34661781.0095 - mae: 2971.8159 - val_loss: 5401764.7034 - val_mae: 2700.5044
Epoch 30/200
10195/10195 - 0s - loss: 33979110.6693 - mae: 2953.6946 - val_loss: 5323525.0906 - val_mae: 2680.0239
Epoch 31/200
10195/10195 - 0s - loss: 33505784.9980 - mae: 2941.4580 - val_loss: 5265220.5689 - val_mae: 2677.5417
Epoch 32/200
10195/10195 - 0s - loss: 33089967.9125 - mae: 2933.0745 - val_loss: 5194920.2952 - val_mae: 2656.8792
Epoch 33/200
10195/10195 - 0s - loss: 32658746.0220 - mae: 2908.9043 - val_loss: 5131490.9263 - val_mae: 2643.5591
Epoch 34/200
10195/10195 - 0s - loss: 32258652.8840 - mae: 2892.4270 - val_loss: 5066278.1908 - val_mae: 2620.7522
Epoch 35/200
10195/10195 - 0s - loss: 32301946.7162 - mae: 2916.3406 - val_loss: 4992398.5922 - val_mae: 2613.7800
Epoch 36/200
10195/10195 - 0s - loss: 31684836.5585 - mae: 2950.2480 - val_loss: 5035429.7730 - val_mae: 2698.8374
Epoch 37/200
10195/10195 - 0s - loss: 31421251.6037 - mae: 3022.6177 - val_loss: 5067411.4494 - val_mae: 2787.7715
Epoch 38/200
10195/10195 - 0s - loss: 31484721.6024 - mae: 3186.4419 - val_loss: 4969008.2284 - val_mae: 2722.7998
Epoch 39/200
10195/10195 - 0s - loss: 30543946.5116 - mae: 2992.0120 - val_loss: 4855349.8545 - val_mae: 2679.1038
Epoch 40/200
10195/10195 - 0s - loss: 30151856.8581 - mae: 3000.0947 - val_loss: 4770754.6664 - val_mae: 2664.1565
Epoch 41/200
10195/10195 - 0s - loss: 29301838.9534 - mae: 2853.9016 - val_loss: 4623431.9835 - val_mae: 2562.2502
Epoch 42/200
10195/10195 - 0s - loss: 29045066.3627 - mae: 2766.8882 - val_loss: 4535374.5272 - val_mae: 2501.6182
Epoch 43/200
10195/10195 - 0s - loss: 28663094.1850 - mae: 2707.2258 - val_loss: 4474656.5844 - val_mae: 2473.7437
Epoch 44/200
10195/10195 - 0s - loss: 28398637.8966 - mae: 2689.7458 - val_loss: 4423665.0783 - val_mae: 2463.4524
Epoch 45/200
10195/10195 - 0s - loss: 28069814.3744 - mae: 2690.7847 - val_loss: 4376541.5748 - val_mae: 2459.1013
Epoch 46/200
10195/10195 - 0s - loss: 27648031.7698 - mae: 2673.3755 - val_loss: 4328765.1652 - val_mae: 2458.3098
Epoch 47/200
10195/10195 - 0s - loss: 27324080.9671 - mae: 2680.5867 - val_loss: 4281693.4279 - val_mae: 2458.8657
Epoch 48/200
10195/10195 - 0s - loss: 26991945.4962 - mae: 2685.0212 - val_loss: 4239926.5533 - val_mae: 2462.6279
Epoch 49/200
10195/10195 - 0s - loss: 26594169.1519 - mae: 2661.8906 - val_loss: 4178658.3039 - val_mae: 2442.8281
Epoch 50/200
10195/10195 - 0s - loss: 26281293.1719 - mae: 2652.1121 - val_loss: 4124419.9886 - val_mae: 2428.3228
Epoch 51/200
10195/10195 - 0s - loss: 25909680.4640 - mae: 2631.5352 - val_loss: 4074729.1648 - val_mae: 2424.6494
Epoch 52/200
10195/10195 - 0s - loss: 25625131.3336 - mae: 2623.2773 - val_loss: 3999893.9913 - val_mae: 2388.9065
Epoch 53/200
10195/10195 - 0s - loss: 25197227.1071 - mae: 2588.4648 - val_loss: 3941536.3043 - val_mae: 2378.5120
Epoch 54/200
10195/10195 - 0s - loss: 24832450.4055 - mae: 2571.8047 - val_loss: 3885973.5222 - val_mae: 2365.1416
Epoch 55/200
10195/10195 - 0s - loss: 24514736.7248 - mae: 2559.2197 - val_loss: 3834000.3249 - val_mae: 2341.5603
Epoch 56/200
10195/10195 - 0s - loss: 24201112.3103 - mae: 2539.5908 - val_loss: 3785890.4668 - val_mae: 2349.1128
Epoch 57/200
10195/10195 - 0s - loss: 24016988.6845 - mae: 2557.4316 - val_loss: 3717133.3835 - val_mae: 2305.5610
Epoch 58/200
10195/10195 - 0s - loss: 23554856.5810 - mae: 2515.2422 - val_loss: 3660750.7378 - val_mae: 2312.8752
Epoch 59/200
10195/10195 - 0s - loss: 23147493.3023 - mae: 2508.4214 - val_loss: 3604710.8677 - val_mae: 2294.6797
Epoch 60/200
10195/10195 - 0s - loss: 22704282.9457 - mae: 2475.3994 - val_loss: 3546701.7860 - val_mae: 2279.1514
Epoch 61/200
10195/10195 - 0s - loss: 22366024.0509 - mae: 2451.1677 - val_loss: 3489045.9732 - val_mae: 2249.8330
Epoch 62/200
10195/10195 - 0s - loss: 22031589.7505 - mae: 2426.5081 - val_loss: 3429795.4371 - val_mae: 2245.1682
Epoch 63/200
10195/10195 - 0s - loss: 21694823.9371 - mae: 2420.9209 - val_loss: 3379597.6783 - val_mae: 2212.4910
Epoch 64/200
10195/10195 - 0s - loss: 21369370.4757 - mae: 2392.9246 - val_loss: 3341839.4144 - val_mae: 2251.3899
Epoch 65/200
10195/10195 - 0s - loss: 21197109.4778 - mae: 2410.9373 - val_loss: 3252438.3705 - val_mae: 2154.1711
Epoch 66/200
10195/10195 - 0s - loss: 20779675.3590 - mae: 2331.9485 - val_loss: 3169007.2208 - val_mae: 2136.6582
Epoch 67/200
10195/10195 - 0s - loss: 20378937.0604 - mae: 2324.2637 - val_loss: 3140786.7503 - val_mae: 2167.2085
Epoch 68/200
10195/10195 - 0s - loss: 19878900.4465 - mae: 2327.1479 - val_loss: 3106459.5085 - val_mae: 2178.9905
Epoch 69/200
10195/10195 - 0s - loss: 19682755.6207 - mae: 2352.9026 - val_loss: 3053050.3840 - val_mae: 2118.8647
Epoch 70/200
10195/10195 - 0s - loss: 19363452.8891 - mae: 2278.8057 - val_loss: 2966893.5842 - val_mae: 2104.2546
Epoch 71/200
10195/10195 - 0s - loss: 18908182.3301 - mae: 2235.8022 - val_loss: 2903825.1792 - val_mae: 2071.8193

Epoch 72/200
10195/10195 - 0s - loss: 18537915.3651 - mae: 2215.4434 - val_loss: 2853835.1844 - val_mae: 2060.3257
Epoch 73/200
10195/10195 - 0s - loss: 18224461.8142 - mae: 2202.3311 - val_loss: 2787659.1792 - val_mae: 2029.5481
Epoch 74/200
10195/10195 - 0s - loss: 17951406.8299 - mae: 2185.6826 - val_loss: 2731142.6876 - val_mae: 1982.8004
Epoch 75/200
10195/10195 - 0s - loss: 17588861.0206 - mae: 2126.1323 - val_loss: 2669555.2137 - val_mae: 1966.0566
Epoch 76/200
10195/10195 - 0s - loss: 17373973.9845 - mae: 2129.2375 - val_loss: 2652543.9764 - val_mae: 2010.4047
Epoch 77/200
10195/10195 - 0s - loss: 16981377.1373 - mae: 2127.9397 - val_loss: 2580785.6233 - val_mae: 1937.6881
Epoch 78/200
10195/10195 - 0s - loss: 16553836.6981 - mae: 2072.2522 - val_loss: 2531585.1787 - val_mae: 1921.9369
Epoch 79/200
10195/10195 - 0s - loss: 16711147.3496 - mae: 2123.9468 - val_loss: 2499441.6748 - val_mae: 1945.5364
Epoch 80/200
10195/10195 - 0s - loss: 17009049.3234 - mae: 2214.5967 - val_loss: 2914793.5366 - val_mae: 2450.6565
Epoch 81/200
10195/10195 - 0s - loss: 17101311.7672 - mae: 2483.4675 - val_loss: 2660007.8600 - val_mae: 2026.6846
Epoch 82/200
10195/10195 - 0s - loss: 15788535.9265 - mae: 2176.0576 - val_loss: 2413959.2339 - val_mae: 1943.8260
Epoch 83/200
10195/10195 - 0s - loss: 15405541.1712 - mae: 2021.6028 - val_loss: 2312097.0092 - val_mae: 1878.8723
Epoch 84/200
10195/10195 - 0s - loss: 14739829.1306 - mae: 1939.9082 - val_loss: 2242102.9018 - val_mae: 1810.8350
Epoch 85/200
10195/10195 - 0s - loss: 14568497.7662 - mae: 1919.0793 - val_loss: 2315619.4380 - val_mae: 1820.2837
Epoch 86/200
10195/10195 - 0s - loss: 16381458.0146 - mae: 2207.0042 - val_loss: 2498965.7529 - val_mae: 2196.3801
Epoch 87/200
10195/10195 - 0s - loss: 14827032.7028 - mae: 2084.7461 - val_loss: 2342915.1135 - val_mae: 1835.5004
Epoch 88/200
10195/10195 - 0s - loss: 14514699.3123 - mae: 1928.9448 - val_loss: 2220447.4030 - val_mae: 1898.7424
Epoch 89/200
10195/10195 - 0s - loss: 13859755.2639 - mae: 1857.8782 - val_loss: 2089219.5570 - val_mae: 1705.8561
Epoch 90/200
10195/10195 - 0s - loss: 13796232.5929 - mae: 1843.5553 - val_loss: 2040584.1094 - val_mae: 1654.4535
Epoch 91/200
10195/10195 - 0s - loss: 13553189.1653 - mae: 1748.1057 - val_loss: 2022039.4753 - val_mae: 1667.9092
Epoch 92/200
10195/10195 - 0s - loss: 13342231.8361 - mae: 1733.6061 - val_loss: 2000493.8046 - val_mae: 1622.2614
Epoch 93/200
10195/10195 - 0s - loss: 13233888.5228 - mae: 1718.7626 - val_loss: 2024163.9854 - val_mae: 1719.0664
Epoch 94/200
10195/10195 - 0s - loss: 13247966.0138 - mae: 1770.1487 - val_loss: 1947903.1446 - val_mae: 1584.3594
Epoch 95/200
10195/10195 - 0s - loss: 12874889.4226 - mae: 1673.3896 - val_loss: 1912545.5935 - val_mae: 1586.1367
Epoch 96/200
10195/10195 - 0s - loss: 12735663.8807 - mae: 1641.4976 - val_loss: 1887940.1246 - val_mae: 1566.6768
Epoch 97/200
10195/10195 - 0s - loss: 12577919.7955 - mae: 1643.7916 - val_loss: 1944397.6214 - val_mae: 1581.6621
Epoch 98/200
10195/10195 - 0s - loss: 13469405.0086 - mae: 1837.7272 - val_loss: 2047720.8403 - val_mae: 1853.9274
Epoch 99/200
10195/10195 - 0s - loss: 12763853.1960 - mae: 1752.7847 - val_loss: 1894266.4357 - val_mae: 1545.6277
Epoch 100/200
10195/10195 - 0s - loss: 12285561.5130 - mae: 1622.1952 - val_loss: 1822697.0756 - val_mae: 1552.1448
Epoch 101/200
10195/10195 - 0s - loss: 12085038.2042 - mae: 1571.4825 - val_loss: 1816985.7788 - val_mae: 1561.7155
Epoch 102/200
10195/10195 - 0s - loss: 12337138.2272 - mae: 1716.2134 - val_loss: 1790275.6203 - val_mae: 1468.3140
Epoch 103/200
10195/10195 - 0s - loss: 11937313.9230 - mae: 1543.7839 - val_loss: 1748596.7714 - val_mae: 1473.0361
Epoch 104/200
10195/10195 - 0s - loss: 11737507.5313 - mae: 1510.0846 - val_loss: 1719798.3624 - val_mae: 1432.9889
Epoch 105/200
10195/10195 - 0s - loss: 11624661.5267 - mae: 1499.3947 - val_loss: 1703640.4501 - val_mae: 1420.5049
Epoch 106/200
10195/10195 - 0s - loss: 11506875.3248 - mae: 1484.7726 - val_loss: 1686275.5942 - val_mae: 1397.5688
Epoch 107/200
10195/10195 - 0s - loss: 11408880.7101 - mae: 1461.6698 - val_loss: 1705199.4968 - val_mae: 1401.4044
Epoch 108/200
10195/10195 - 0s - loss: 12055380.0848 - mae: 1608.5618 - val_loss: 1882315.9208 - val_mae: 1757.4506
Epoch 109/200
10195/10195 - 0s - loss: 11706057.9665 - mae: 1608.1011 - val_loss: 1740839.4299 - val_mae: 1424.5553
Epoch 110/200
10195/10195 - 0s - loss: 11305452.1165 - mae: 1535.7478 - val_loss: 1668706.0055 - val_mae: 1401.1451
Epoch 111/200
10195/10195 - 0s - loss: 11037066.1559 - mae: 1432.7981 - val_loss: 1649858.7027 - val_mae: 1424.6593
Epoch 112/200
10195/10195 - 0s - loss: 11002327.0488 - mae: 1468.0516 - val_loss: 1609757.2053 - val_mae: 1310.8138
Epoch 113/200
10195/10195 - 0s - loss: 10854277.8752 - mae: 1390.4227 - val_loss: 1578853.1738 - val_mae: 1302.9362
Epoch 114/200
10195/10195 - 0s - loss: 10750823.8497 - mae: 1350.5259 - val_loss: 1617629.3883 - val_mae: 1401.0183
Epoch 115/200
10195/10195 - 0s - loss: 11018083.7974 - mae: 1491.4711 - val_loss: 1614532.3978 - val_mae: 1328.0033
Epoch 116/200
10195/10195 - 0s - loss: 10708412.0257 - mae: 1368.0067 - val_loss: 1548203.8923 - val_mae: 1284.0870
Epoch 117/200
10195/10195 - 0s - loss: 10549287.1893 - mae: 1315.5087 - val_loss: 1526252.0207 - val_mae: 1243.0751
Epoch 118/200
10195/10195 - 0s - loss: 10457289.7617 - mae: 1306.8530 - val_loss: 1514228.0539 - val_mae: 1229.1890
Epoch 119/200
10195/10195 - 0s - loss: 10389392.5690 - mae: 1294.9723 - val_loss: 1504265.8715 - val_mae: 1217.5476
Epoch 120/200
10195/10195 - 0s - loss: 10366722.0408 - mae: 1286.0427 - val_loss: 1549790.8041 - val_mae: 1344.2791
Epoch 121/200
10195/10195 - 0s - loss: 10526194.1133 - mae: 1398.3208 - val_loss: 1506656.6740 - val_mae: 1219.2001
Epoch 122/200
10195/10195 - 0s - loss: 10264760.4804 - mae: 1278.2864 - val_loss: 1470498.9630 - val_mae: 1182.8201
Epoch 123/200
10195/10195 - 0s - loss: 10156075.2819 - mae: 1242.0787 - val_loss: 1465491.7556 - val_mae: 1189.4901
Epoch 124/200
10195/10195 - 0s - loss: 10096199.8956 - mae: 1255.8123 - val_loss: 1450062.9997 - val_mae: 1158.0892
Epoch 125/200
10195/10195 - 0s - loss: 10025794.4769 - mae: 1232.8843 - val_loss: 1441742.6431 - val_mae: 1168.5479
Epoch 126/200
10195/10195 - 0s - loss: 10031359.6295 - mae: 1231.1371 - val_loss: 1447231.4855 - val_mae: 1204.6735
Epoch 127/200
10195/10195 - 0s - loss: 9912065.9243 - mae: 1223.6675 - val_loss: 1421190.5557 - val_mae: 1139.4116
Epoch 128/200
10195/10195 - 0s - loss: 9874935.0252 - mae: 1226.1309 - val_loss: 1413777.6222 - val_mae: 1125.9634
Epoch 129/200
10195/10195 - 0s - loss: 9818197.7789 - mae: 1204.6982 - val_loss: 1431630.8753 - val_mae: 1146.0651
Epoch 130/200
10195/10195 - 0s - loss: 9974126.8513 - mae: 1265.9370 - val_loss: 1459940.1876 - val_mae: 1288.2269
Epoch 131/200
10195/10195 - 0s - loss: 9773915.8587 - mae: 1224.1266 - val_loss: 1393668.3451 - val_mae: 1105.6328
Epoch 132/200
10195/10195 - 0s - loss: 9684183.5403 - mae: 1180.0048 - val_loss: 1379357.3412 - val_mae: 1106.8698
Epoch 133/200
10195/10195 - 0s - loss: 9620580.7384 - mae: 1174.1476 - val_loss: 1370425.3515 - val_mae: 1095.2578
Epoch 134/200
10195/10195 - 0s - loss: 9573107.0915 - mae: 1178.2324 - val_loss: 1362439.2596 - val_mae: 1076.7874
Epoch 135/200
10195/10195 - 0s - loss: 9512461.0184 - mae: 1143.8262 - val_loss: 1360917.0555 - val_mae: 1072.7520
Epoch 136/200
10195/10195 - 0s - loss: 9690013.2718 - mae: 1226.5244 - val_loss: 1573239.5797 - val_mae: 1567.6821
Epoch 137/200
10195/10195 - 0s - loss: 10225423.8209 - mae: 1475.7980 - val_loss: 1356225.2251 - val_mae: 1074.7771
Epoch 138/200
10195/10195 - 0s - loss: 9678728.4915 - mae: 1320.1755 - val_loss: 1393258.7630 - val_mae: 1168.6730
Epoch 139/200
10195/10195 - 0s - loss: 9477740.9723 - mae: 1193.1670 - val_loss: 1358328.6323 - val_mae: 1147.9310
Epoch 140/200
10195/10195 - 0s - loss: 9326291.0826 - mae: 1123.2711 - val_loss: 1315466.7407 - val_mae: 1030.4586
Epoch 141/200
10195/10195 - 0s - loss: 9253984.0398 - mae: 1096.2748 - val_loss: 1307843.9445 - val_mae: 1033.9146
Epoch 142/200
10195/10195 - 0s - loss: 9212198.3535 - mae: 1090.8823 - val_loss: 1300168.7992 - val_mae: 1021.0795

Epoch 143/200
10195/10195 - 0s - loss: 9196101.7895 - mae: 1097.4257 - val_loss: 1293001.9880 - val_mae: 1017.4973
Epoch 144/200
10195/10195 - 0s - loss: 9211069.9852 - mae: 1104.0864 - val_loss: 1326921.0469 - val_mae: 1147.8492
Epoch 145/200
10195/10195 - 0s - loss: 9157390.9343 - mae: 1119.3478 - val_loss: 1278845.1166 - val_mae: 1004.6937
Epoch 146/200
10195/10195 - 0s - loss: 9044901.4670 - mae: 1077.8495 - val_loss: 1273462.3715 - val_mae: 1014.9467
Epoch 147/200
10195/10195 - 0s - loss: 9011916.3480 - mae: 1059.1689 - val_loss: 1267312.3451 - val_mae: 1013.2977
Epoch 148/200
10195/10195 - 0s - loss: 8965847.0470 - mae: 1053.1740 - val_loss: 1259289.6438 - val_mae: 1002.1268
Epoch 149/200
10195/10195 - 0s - loss: 8929643.7192 - mae: 1053.4242 - val_loss: 1251773.6444 - val_mae: 993.4289
Epoch 150/200
10195/10195 - 0s - loss: 8895566.7518 - mae: 1045.8219 - val_loss: 1249892.5751 - val_mae: 1008.4145
Epoch 151/200
10195/10195 - 0s - loss: 8859611.5990 - mae: 1046.9583 - val_loss: 1237317.4855 - val_mae: 973.6356
Epoch 152/200
10195/10195 - 0s - loss: 8820330.4542 - mae: 1042.2196 - val_loss: 1234802.1644 - val_mae: 968.5518
Epoch 153/200
10195/10195 - 0s - loss: 8798080.4960 - mae: 1028.3953 - val_loss: 1238599.1636 - val_mae: 1020.5481
Epoch 154/200
10195/10195 - 0s - loss: 8772533.0962 - mae: 1046.0234 - val_loss: 1218027.8388 - val_mae: 953.4485
Epoch 155/200
10195/10195 - 0s - loss: 8725928.0773 - mae: 1022.1201 - val_loss: 1212320.3895 - val_mae: 946.9492
Epoch 156/200
10195/10195 - 0s - loss: 8687682.1636 - mae: 1015.1134 - val_loss: 1214582.2430 - val_mae: 987.6395
Epoch 157/200
10195/10195 - 0s - loss: 8648479.4362 - mae: 1014.9759 - val_loss: 1197277.3145 - val_mae: 941.7509
Epoch 158/200
10195/10195 - 0s - loss: 8602623.6785 - mae: 1018.5119 - val_loss: 1195385.4023 - val_mae: 938.6083
Epoch 159/200
10195/10195 - 0s - loss: 8572855.0813 - mae: 1009.4455 - val_loss: 1185977.0243 - val_mae: 944.5162
Epoch 160/200
10195/10195 - 0s - loss: 8524417.9872 - mae: 989.5068 - val_loss: 1251406.3847 - val_mae: 1093.8473
Epoch 161/200
10195/10195 - 0s - loss: 9338091.4745 - mae: 1380.7925 - val_loss: 1270724.5960 - val_mae: 1253.3564
Epoch 162/200
10195/10195 - 0s - loss: 8748580.8449 - mae: 1093.8834 - val_loss: 1192664.5324 - val_mae: 1008.3458
Epoch 163/200
10195/10195 - 0s - loss: 8527560.1590 - mae: 1024.3749 - val_loss: 1203284.1680 - val_mae: 1089.7845
Epoch 164/200
10195/10195 - 0s - loss: 8417635.1073 - mae: 1016.5505 - val_loss: 1158993.4612 - val_mae: 930.4315
Epoch 165/200
10195/10195 - 0s - loss: 8327489.9305 - mae: 990.1427 - val_loss: 1156772.7641 - val_mae: 915.9572
Epoch 166/200
10195/10195 - 0s - loss: 8399851.7170 - mae: 1025.1444 - val_loss: 1166463.7572 - val_mae: 993.0520
Epoch 167/200
10195/10195 - 0s - loss: 8263572.1301 - mae: 988.5203 - val_loss: 1137857.1394 - val_mae: 897.4724
Epoch 168/200
10195/10195 - 0s - loss: 8222476.3517 - mae: 970.7150 - val_loss: 1130742.7938 - val_mae: 895.4193
Epoch 169/200
10195/10195 - 0s - loss: 8192951.4708 - mae: 960.6808 - val_loss: 1124102.8546 - val_mae: 891.4836
Epoch 170/200
10195/10195 - 0s - loss: 8165465.3093 - mae: 953.0967 - val_loss: 1152800.0632 - val_mae: 1025.3202
Epoch 171/200
10195/10195 - 0s - loss: 8225662.9347 - mae: 1015.6712 - val_loss: 1111812.1289 - val_mae: 889.6666
Epoch 172/200
10195/10195 - 0s - loss: 8141886.1756 - mae: 976.1130 - val_loss: 1102966.2995 - val_mae: 871.1167
Epoch 173/200
10195/10195 - 0s - loss: 8091243.0383 - mae: 965.0134 - val_loss: 1127183.6390 - val_mae: 965.1097
Epoch 174/200
10195/10195 - 0s - loss: 8142727.8453 - mae: 1024.5173 - val_loss: 1097375.7904 - val_mae: 904.3216
Epoch 175/200
10195/10195 - 0s - loss: 8059586.3069 - mae: 957.4361 - val_loss: 1137481.3685 - val_mae: 1060.2003
Epoch 176/200
10195/10195 - 0s - loss: 8058142.0811 - mae: 1015.4964 - val_loss: 1079801.5381 - val_mae: 856.1976
Epoch 177/200
10195/10195 - 0s - loss: 7970713.7155 - mae: 948.4830 - val_loss: 1073766.9362 - val_mae: 852.6191
Epoch 178/200
10195/10195 - 0s - loss: 7913421.1352 - mae: 928.8164 - val_loss: 1077974.5667 - val_mae: 907.7034
Epoch 179/200
10195/10195 - 0s - loss: 7884241.0402 - mae: 926.0398 - val_loss: 1062490.6635 - val_mae: 846.8374
Epoch 180/200
10195/10195 - 0s - loss: 7854202.1179 - mae: 917.8554 - val_loss: 1062350.9882 - val_mae: 877.6949
Epoch 181/200
10195/10195 - 0s - loss: 7824425.7805 - mae: 910.9235 - val_loss: 1061865.8556 - val_mae: 889.2947
Epoch 182/200
10195/10195 - 0s - loss: 7820899.8252 - mae: 920.5173 - val_loss: 1272668.1578 - val_mae: 1397.0704
Epoch 183/200
10195/10195 - 0s - loss: 9085720.2780 - mae: 1562.8435 - val_loss: 1157732.4196 - val_mae: 1200.0814
Epoch 184/200
10195/10195 - 0s - loss: 8244139.8424 - mae: 1182.2095 - val_loss: 1153539.1296 - val_mae: 1197.4771
Epoch 185/200
10195/10195 - 0s - loss: 8013077.9948 - mae: 1097.6608 - val_loss: 1033328.4924 - val_mae: 839.8198
Epoch 186/200
10195/10195 - 0s - loss: 7727448.2427 - mae: 919.5474 - val_loss: 1033524.2477 - val_mae: 874.4698
Epoch 187/200
10195/10195 - 0s - loss: 7682400.1781 - mae: 907.9178 - val_loss: 1028587.6941 - val_mae: 875.6590
Epoch 188/200
10195/10195 - 0s - loss: 7662703.9081 - mae: 912.8815 - val_loss: 1013762.9929 - val_mae: 822.6408
Epoch 189/200
10195/10195 - 0s - loss: 7613522.2656 - mae: 900.5776 - val_loss: 1012433.8625 - val_mae: 834.8148
Epoch 190/200
10195/10195 - 0s - loss: 7600682.6866 - mae: 890.7184 - val_loss: 1030209.2332 - val_mae: 925.5469
Epoch 191/200
10195/10195 - 0s - loss: 7589192.6043 - mae: 931.1834 - val_loss: 1002904.5802 - val_mae: 810.7734
Epoch 192/200
10195/10195 - 0s - loss: 7555426.9763 - mae: 897.8395 - val_loss: 996733.6841 - val_mae: 812.1106
Epoch 193/200
10195/10195 - 0s - loss: 7514630.1597 - mae: 886.0746 - val_loss: 991539.1159 - val_mae: 806.0232
Epoch 194/200
10195/10195 - 0s - loss: 7505397.5840 - mae: 902.9628 - val_loss: 1006012.4136 - val_mae: 880.3694
Epoch 195/200
10195/10195 - 0s - loss: 7490319.3698 - mae: 924.9342 - val_loss: 1000155.7286 - val_mae: 886.6967
Epoch 196/200
10195/10195 - 0s - loss: 7448684.1620 - mae: 886.1599 - val_loss: 989433.0271 - val_mae: 851.8678
Epoch 197/200
10195/10195 - 0s - loss: 7413944.3860 - mae: 885.6946 - val_loss: 974402.6605 - val_mae: 792.1985
Epoch 198/200
10195/10195 - 0s - loss: 7388746.1953 - mae: 867.3015 - val_loss: 970057.8614 - val_mae: 792.1667
Epoch 199/200
10195/10195 - 0s - loss: 7379166.2878 - mae: 866.0742 - val_loss: 1006879.3797 - val_mae: 957.8032
Epoch 200/200
10195/10195 - 0s - loss: 7379518.0339 - mae: 922.1041 - val_loss: 968239.9257 - val_mae: 807.2937

In [63]:
test_data=np.load('Testing_Data.npz')

In [64]:
predictions=model.predict(test_data['inputs'])

In [86]:
predictions[:5]

array([[7478.737 ],
       [7969.3726],
       [ 588.2435],
       [8248.996 ],
       [ 758.3948]], dtype=float32)

In [101]:
test_data['target'].flatten().tolist().index(test_data['target'].max())

1021

In [65]:
rss=((predictions.flatten()-test_data['target'])**2).sum()
tss=((test_data['target']-test_data['target'].mean())**2).sum()
r2=1-(rss/tss)
r2

0.9115566208937713

In [66]:
features2.columns

Index(['Overall', 'Potential', 'Value', 'Wage', 'Special',
       'International Reputation', 'ShortPassing', 'Reactions', 'Vision',
       'Composure'],
      dtype='object')

In [67]:
model.save('Fifa19_Model.h5')

In [68]:
import pickle

In [69]:
pwd

'C:\\Users\\Aditya\\OneDrive\\Desktop\\Grras\\Practice\\Fifa19_Rep\\fifa19'

In [70]:
fp=open(r'C:\Users\Aditya\OneDrive\Desktop\Grras\Practice\fifa19\Project\Fifa19_model.pkl','wb')

In [71]:
pickle.dump(model,fp)

TypeError: can't pickle _thread._local objects

In [ ]:
dir(model)

In [ ]:
json_file=model.to_json()

In [ ]:
dir(json_file)

In [ ]:
json_file